CREATE TABLE `equipment` (
	`id` int AUTO_INCREMENT NOT NULL,
	`row_no` int,
	`code_id` varchar(64),
	`plan_name` varchar(255),
	`equipment_type` varchar(255),
	`equipment_name` text NOT NULL,
	`target` text,
	`budget_2566` decimal(15,2) DEFAULT '0',
	`budget_2567` decimal(15,2) DEFAULT '0',
	`budget_2568` decimal(15,2) DEFAULT '0',
	`budget_2569` decimal(15,2) DEFAULT '0',
	`budget_2570` decimal(15,2) DEFAULT '0',
	`total_budget` decimal(15,2) DEFAULT '0',
	`department` varchar(255),
	`plan_book` varchar(255),
	`page_no` varchar(50),
	`item_no` varchar(50),
	`recheck` varchar(255),
	`source_info` varchar(255),
	`old_code_id` varchar(64),
	`budget_status` varchar(100),
	`budget_year_received` varchar(100),
	`actual_budget_received` decimal(15,2) DEFAULT '0',
	`action_plan_count` int DEFAULT 0,
	`action_plan_name` text,
	`check_pdf` varchar(255),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `equipment_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`row_no` int,
	`code_id` varchar(64),
	`strategy` varchar(255),
	`plan_name` varchar(255),
	`project_name` text NOT NULL,
	`target` text,
	`budget_2566` decimal(15,2) DEFAULT '0',
	`budget_2567` decimal(15,2) DEFAULT '0',
	`budget_2568` decimal(15,2) DEFAULT '0',
	`budget_2569` decimal(15,2) DEFAULT '0',
	`budget_2570` decimal(15,2) DEFAULT '0',
	`total_budget` decimal(15,2) DEFAULT '0',
	`department` varchar(255),
	`work_type` varchar(100),
	`village_no` varchar(100),
	`plan_book` varchar(255),
	`page_no` varchar(50),
	`item_no` varchar(50),
	`recheck` varchar(255),
	`source_info` varchar(255),
	`old_code_id` varchar(64),
	`budget_status` varchar(100),
	`budget_year_received` varchar(100),
	`actual_budget_received` decimal(15,2) DEFAULT '0',
	`action_plan_count` int DEFAULT 0,
	`action_plan_name` text,
	`check_pdf` varchar(255),
	`is_exceeded` int NOT NULL DEFAULT 0,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `projects_id` PRIMARY KEY(`id`)
);
